### ISSUE TITLE
PublicTypeVersion NOT actually incrementing public version (?)

### ISSUE THREAD

**Issue by SHxKM** [aws-cloudformation/cloudformation-resource-schema#130]
Following up on the thread where I reported an issue (#129) which actually turned out to be an issue on the CFN side, I used a workaround suggested there by @ugudip for publishing a public type:

> Hey SHxKM,
> Thanks for the template. I don't think it makes any difference by changing the resource name you give, you are allowed to give any name as a logical Id. Your template looks good at first glance, but I will need to investigate on why it isn't working for you. I will get back to you shortly with my findings. Meanwhile, as a workaround, can you please try by giving TypeName and Type instead of Arn for PublicTypeVersion resource?

So I've used this template to register the custom resource in almost all regions:

```
Resources:
  MyTypePrivateTypeVersion: 
    Type: AWS::CloudFormation::ResourceVersion
    Properties:
      SchemaHandlerPackage: !Ref SchemaHandlerUrl
      TypeName: MyCompany::MyCategory::MyType
  MyTypeResourceDefaultVersion:    
    Type: AWS::CloudFormation::ResourceDefaultVersion
    DependsOn: MyTypePrivateTypeVersion
    Properties:
      TypeVersionArn: !Ref MyTypePrivateTypeVersion
  CustomTypePublisher:
    Type: AWS::CloudFormation::Publisher
    DependsOn: MyTypeResourceDefaultVersion
    Properties:
      AcceptTermsAndConditions: true
  MyTypePublicTypeVersion:     
    Type: AWS::CloudFormation::PublicTypeVersion
    DependsOn: CustomTypePublisher
    Properties:
      LogDeliveryBucket: my-s3-logs-bucket
      PublicVersionNumber: !Ref VersionToPublish
      Type: RESOURCE
      TypeName: MyCompany::MyCategory::MyType
```

The registration of version 1.0.0 was successful. 

However, when I tried to update the version to `1.0.1`, even though the operation was "successful", the version isn't really bumped. 

- The operation was marked as successful 
- The stack instance has a status of `UPDATE_COMPLETE` 
- under the StackSet the stack instance its status is `CURRENT`
- In the `Parameters` part of the stack instance, the version is `1.0.1`

Despite all this, almost 40 minutes after the "successful" publishing, the version showing in the public registry is still `1.0.0`. It seems that there is no real sync whatsoever.

There is one detail that may be affecting this process. When I registered the types initially, I used:

```
aws cloudformation create-stack-instances --stack-set-name my-stack-set-name --accounts '["XXXXX"]'  --regions '["LIST OF REGIONS HERE"]' --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1,RegionConcurrencyType=PARALLEL
```

The StackSet parameters were:

```YAML
VersionToPublish=1.0.1 # this may be the culprit 
SchemaHandlerUrl=s3://my-bucket/my-handler.zip
```

Notice the `1.0.1` as the parameter value. What this did: it published the public types successfully, but as version `1.0.0` - this is documented in `PublicTypeVersion`:

> The first time you publish a type, AWS CloudFormation sets the version number to 1.0.0, regardless of the value you specify.

Any attempts to then update the template failed, or reported "No updates are to be performed" (because the template showed `1.0.1`, even though the actual underlying resource version was still `1.0.0`, so we were stuck. As a workaround, I've uploaded an identical `.zip` to `my-handler.zip`, and updated the stack-set changing only the handler URL to the new (yet identical zip):

```
aws cloudformation update-stack-set --stack-set-name my-stack-set-name --template-body "file://my-public-type-stackset.yaml" --region us-east-1 --parameters ParameterKey=VersionToPublish,ParameterValue=1.0.1 ParameterKey=SchemaHandlerUrl,ParameterValue=s3://my-bucket/my-handler-updated.zip
```

This operation was successful, but as I detailed above, it does not seem to actually publish the new version. What is the proper way to "force" all stack instances to update, given the same parameters?

**Comment by SHxKM** [comment]
Even expanding the dependencies for `MyTypePublicTypeVersion` and changing the `zip` handler _once again_, results in the same outcome: The update operation is successful, no new version is actually published.

```
  MyTypePublicTypeVersion:     
    Type: AWS::CloudFormation::PublicTypeVersion
    DependsOn: 
      - CustomTypePublisher
      - MyTypePrivateTypeVersion
      - MyTypeResourceDefaultVersion
    Properties:
      LogDeliveryBucket: my-s3-logs-bucket
      PublicVersionNumber: !Ref VersionToPublish
      Type: RESOURCE
      TypeName: MyCompany::MyCategory::MyType
```
